name: Changelog CI

on:
  pull_request:
    types: [ opened, synchronize ]

  workflow_dispatch:
    inputs:
      release_version:
        description: 'Set Release Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Changelog CI
        uses: MoonieGZ/changelog-ci-cz@v1.0.2
        with:
          changelog_filename: CHANGELOG.md
          config_file: .github/changelog-ci-config.yml
          github_token: ${{ secrets.GITHUB_TOKEN }}